/**
 * DB-2 recipe: NestJS + TypeORM `sqljs` module-boundary integration spec generator.
 *
 * Productizes the validated sqljs proof recipe. Given an eligible service-method
 * target and its entity, it writes a REAL Vitest integration spec under
 * `orangepro_generated/` that boots the smallest Nest testing module against an
 * in-memory `sqljs` (npm `sql.js` WASM) datasource, seeds rows through the REAL
 * repository, and calls the target method for real — NEVER importing, mocking, or
 * replacing the target service. It emits nothing that mints Proven: the generated
 * spec is a local file, and Proven still flows ONLY from the unchanged dynamic
 * targeted-proof oracle (`opProveLoop`/`opDynamicProof`) once this spec makes the
 * baseline runnable. See docs/local-proof-kit.md and the db-backed-repo spec.
 *
 * Template-based for the Nest + TypeORM + sqljs shape (entity with a seedable text
 * column, service method returning the seeded rows). Generalizing to arbitrary repo
 * shapes is a follow-up.
 */
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, isAbsolute, posix, relative, resolve } from "node:path";

import { GENERATED_DIR } from "../generate/runHints.js";
import { isEligibleProvableTarget } from "../autoProve.js";
import { resolveTargetSymbol } from "../ledger.js";
import { loadGraph, workspacePaths } from "../workspace.js";

const GENERATED_HEADER = "// GENERATED BY OrangePro Local Proof Kit — recipe db-sqljs. Safe to edit or delete.";

/** A trusted-local repo-prep profile emitted alongside a recipe (DB-1 shape). */
export interface ProofSetupProfile {
  id: string;
  label: string;
  setup_commands: Array<{ command: string; args?: string[]; timeout_ms?: number }>;
  test_env?: string[];
  confidence: "exact" | "candidate";
  reason: string;
}

/** An inert mutation the recipe's paired DB-3 validation drives through the oracle. */
export interface RecipeMutation {
  method: string;
  replacement: string;
  replacement_mode: "return-json";
}

export interface DbSqljsRecipeOptions {
  /** sym:<file>#<Class>.<method> of the target service method. */
  target_symbol: string;
  /** <file>#<Entity> (optionally sym:-prefixed) of the persisted entity. */
  entity: string;
  /** Output spec path, must live under orangepro_generated/. */
  out: string;
  /** Source checkout containing the service/entity (defaults to root). */
  source?: string;
  /** Seedable text column asserted by the spec (default "name"). */
  seed_field?: string;
}

export interface DbSqljsRecipeResult {
  spec_path: string;
  spec_rel: string;
  target_symbol: string;
  entity_id: string;
  service_class: string;
  entity_class: string;
  method: string;
  seed_field: string;
  runner: "vitest";
  vitest_config: string;
  profile: ProofSetupProfile;
  /** DB-3 validation plan: genuine kills, equivalent survives — never merge if equivalent proves. */
  genuine_mutation: RecipeMutation;
  equivalent_mutation: RecipeMutation;
}

/**
 * Key-name secret filter mirroring the oracle's `isSecretEnvKey` (spike). Recipe-side
 * defense-in-depth so a secret-looking `test_env` key never reaches setup/report/ledger;
 * the oracle rejects it downstream too.
 */
function isSecretEnvKey(key: string): boolean {
  return /TOKEN|SECRET|PASSWORD|API[_-]?KEY|ACCESS[_-]?KEY|PRIVATE[_-]?KEY|SECRET[_-]?KEY|PASSPHRASE|CREDENTIAL|PIN|AUTH|COOKIE|SESSION/i.test(key);
}

function assertNonSecretTestEnv(testEnv: string[]): void {
  for (const entry of testEnv) {
    const key = entry.split("=", 1)[0] ?? "";
    if (isSecretEnvKey(key)) {
      throw new Error(`recipe db-sqljs: secret-looking test_env key is not allowed: ${key}`);
    }
  }
}

/** Split `sym:file#Class.member` / `file#Class` into file + dotted symbol name. */
function parseSymbolRef(ref: string): { file: string; symbol: string } {
  const stripped = ref.replace(/^sym:/, "");
  const hash = stripped.indexOf("#");
  if (hash <= 0 || hash === stripped.length - 1) {
    throw new Error(`recipe db-sqljs: expected <file>#<Symbol>, got: ${ref}`);
  }
  return { file: stripped.slice(0, hash).split(/[\\/]+/).join("/"), symbol: stripped.slice(hash + 1) };
}

/** Extensionless posix import specifier from the spec dir to a source file. */
function importSpecifier(fromDir: string, toFileRel: string): string {
  const noExt = toFileRel.replace(/\.[cm]?[jt]sx?$/i, "");
  let rel = posix.relative(fromDir, noExt);
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

function isTsJsFile(file: string): boolean {
  return /\.[cm]?[jt]sx?$/i.test(file);
}

function sqljsResolvable(sourceRoot: string): boolean {
  try {
    createRequire(resolve(sourceRoot, "package.json")).resolve("sql.js");
    return true;
  } catch {
    return false;
  }
}

/**
 * Build the emitted setup profile. When sql.js is resolvable the profile is `exact`
 * (auto-runnable) with a quote-free presence check; otherwise it is a `candidate`
 * that surfaces the install instruction but is NOT auto-run (DB-1: no npm-install
 * guessing on the user's checkout). Secret-looking test_env keys are rejected.
 */
export function buildTypeormSqljsNestProfile(input: { sqljsResolvable: boolean; testEnv?: string[]; vitestConfig: string }): ProofSetupProfile {
  const testEnv = input.testEnv ?? [];
  assertNonSecretTestEnv(testEnv);
  if (input.sqljsResolvable) {
    // Exact: sql.js is already resolvable and the sqljs driver runs fully in-memory,
    // so there is nothing to prepare in the source checkout before the oracle copies it.
    // (Presence was verified at generation time.) Empty setup ⇒ opProveLoop proceeds
    // straight to the unchanged oracle.
    return {
      id: "typeorm-sqljs-nest",
      label: "NestJS + TypeORM sqljs in-memory integration",
      setup_commands: [],
      test_env: testEnv,
      confidence: "exact",
      reason: `sql.js is resolvable; the sqljs driver runs fully in-memory (no external DB) — no setup needed. Runner: vitest via ${input.vitestConfig} (unplugin-swc emits decorator metadata for Nest DI + TypeORM).`
    };
  }
  return {
    id: "typeorm-sqljs-nest",
    label: "NestJS + TypeORM sqljs in-memory integration",
    setup_commands: [{ command: "npm", args: ["install", "--no-save", "sql.js"] }],
    test_env: testEnv,
    confidence: "candidate",
    reason: "sql.js is not resolvable. Install it (`npm install sql.js`) then re-prove. Candidate: not auto-run on your checkout."
  };
}

function renderSpec(input: {
  entityImport: string;
  entityClass: string;
  serviceImport: string;
  serviceClass: string;
  method: string;
  seedField: string;
}): string {
  const { entityImport, entityClass, serviceImport, serviceClass, method, seedField } = input;
  return `${GENERATED_HEADER}
import "reflect-metadata";
import { Test, type TestingModule } from "@nestjs/testing";
import { TypeOrmModule, getRepositoryToken } from "@nestjs/typeorm";
import type { Repository } from "typeorm";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { ${entityClass} } from "${entityImport}";
import { ${serviceClass} } from "${serviceImport}";

// Boots the smallest Nest testing module against an in-memory sqljs datasource and
// exercises ${serviceClass}.${method} through the REAL repository. The target service
// is imported and constructed by Nest DI — never mocked, replaced, or stubbed — so the
// dynamic targeted-proof oracle can credit Proven to the real method body.
describe("${serviceClass}.${method} (sqljs integration)", () => {
  let moduleRef: TestingModule;
  let service: ${serviceClass};
  let repository: Repository<${entityClass}>;

  beforeAll(async () => {
    moduleRef = await Test.createTestingModule({
      imports: [
        TypeOrmModule.forRoot({
          type: "sqljs",
          autoSave: false,
          synchronize: true,
          entities: [${entityClass}]
        }),
        TypeOrmModule.forFeature([${entityClass}])
      ],
      providers: [${serviceClass}]
    }).compile();

    service = moduleRef.get(${serviceClass});
    repository = moduleRef.get(getRepositoryToken(${entityClass}));
    await repository.save([{ ${seedField}: "alpha" }, { ${seedField}: "beta" }]);
  });

  afterAll(async () => {
    await moduleRef?.close();
  });

  it("returns seeded ${entityClass} rows through the real repository", async () => {
    const rows = await service.${method}();
    expect(rows.map((row) => row.${seedField})).toEqual(["alpha", "beta"]);
    expect(rows).toHaveLength(2);
  });
});
`;
}

/**
 * Generate the sqljs integration spec + setup profile for an eligible service-method
 * target. Writes ONLY under orangepro_generated/, never overwrites, never escapes root.
 * Refuses targets that do not pass the shared auto-prove eligibility predicate.
 */
export function opRecipeDbSqljs(root: string, opts: DbSqljsRecipeOptions): DbSqljsRecipeResult {
  if (!opts.target_symbol) throw new Error("recipe db-sqljs requires --target-symbol sym:<file>#<Class>.<method>.");
  if (!opts.entity) throw new Error("recipe db-sqljs requires --entity <file>#<Entity>.");
  if (!opts.out) throw new Error("recipe db-sqljs requires --out orangepro_generated/<name>.sqljs.spec.ts.");

  const graph = loadGraph(workspacePaths(root).graphPath);
  const resolved = resolveTargetSymbol(graph, opts.target_symbol);
  if (!resolved) {
    throw new Error(`recipe db-sqljs: --target-symbol did not resolve to exactly one CodeSymbol: ${opts.target_symbol}`);
  }
  const node = graph.nodes.find((n) => n.external_id === resolved);
  // SAME trust barrier as auto-prove target selection: never build a recipe for an
  // excluded/infra/non-entrypoint symbol (Selection Rules). Proof is gated downstream
  // too, but refusing here keeps recipes off plumbing.
  if (!isEligibleProvableTarget(node)) {
    throw new Error(
      `recipe db-sqljs: ${resolved} is not an eligible provable target ` +
        "(requires kind=CodeSymbol, denominator_eligible, behavior_surface=entrypoint_adjacent, no denominator_reason_code, TS/JS)."
    );
  }

  const target = parseSymbolRef(resolved);
  const targetParts = target.symbol.split(".").filter(Boolean);
  const method = targetParts.pop();
  const serviceClass = targetParts.join(".");
  if (!method || !serviceClass) {
    throw new Error(`recipe db-sqljs: could not derive <Class>.<method> from ${resolved}.`);
  }
  // Resolve --entity through the graph exactly like --target-symbol: it must be an in-root TS/JS
  // CodeSymbol, never an unresolved / out-of-root path. (Graph nodes are in-root by construction, so
  // resolution enforces containment; the explicit path guard gives a clear early error.)
  const entityRef = parseSymbolRef(opts.entity);
  const entityFileRel = entityRef.file.split(/[\\/]+/).join("/");
  if (isAbsolute(entityRef.file) || entityFileRel.startsWith("../") || entityFileRel.includes("/../")) {
    throw new Error(`recipe db-sqljs: --entity file must be a relative path inside the source root: ${entityRef.file}`);
  }
  const entityResolved = resolveTargetSymbol(graph, `sym:${entityRef.file}#${entityRef.symbol}`);
  if (!entityResolved) {
    throw new Error(
      `recipe db-sqljs: --entity did not resolve to an existing CodeSymbol in the graph: ${opts.entity}. ` +
        "Analyze the repo first and pass an entity class inside the source root."
    );
  }
  const resolvedEntity = parseSymbolRef(entityResolved);
  const entityClass = resolvedEntity.symbol.split(".").filter(Boolean).pop() ?? "";
  if (!entityClass) throw new Error(`recipe db-sqljs: could not derive entity class from ${entityResolved}.`);
  if (!isTsJsFile(resolvedEntity.file)) throw new Error(`recipe db-sqljs: entity file must be TS/JS: ${resolvedEntity.file}`);

  const seedField = opts.seed_field?.trim() || "name";
  if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(seedField)) {
    throw new Error(`recipe db-sqljs: --seed-field must be a valid identifier: ${seedField}`);
  }

  const sourceRoot = resolve(opts.source ?? root);
  const outRel = opts.out.split(/[\\/]+/).join("/");
  if (isAbsolute(opts.out) || outRel.startsWith("../") || outRel.includes("/../")) {
    throw new Error(`recipe db-sqljs: --out must be a relative path inside the source root: ${opts.out}`);
  }
  const specAbs = resolve(sourceRoot, outRel);
  const generatedRoot = resolve(sourceRoot, GENERATED_DIR);
  const withinGenerated = specAbs === generatedRoot || specAbs.startsWith(`${generatedRoot}/`);
  if (!withinGenerated) {
    throw new Error(`recipe db-sqljs: --out must live under ${GENERATED_DIR}/ (got ${outRel}).`);
  }
  if (!/\.(spec|test)\.[cm]?tsx?$/i.test(outRel)) {
    throw new Error(`recipe db-sqljs: --out must be a .spec.ts / .test.ts file (got ${outRel}).`);
  }
  if (existsSync(specAbs)) {
    throw new Error(`recipe db-sqljs: refusing to overwrite existing file ${outRel}. Delete it or choose another --out.`);
  }

  const specDir = posix.dirname(outRel);
  const spec = renderSpec({
    entityImport: importSpecifier(specDir, resolvedEntity.file),
    entityClass,
    serviceImport: importSpecifier(specDir, target.file),
    serviceClass,
    method,
    seedField
  });

  mkdirSync(dirname(specAbs), { recursive: true });
  writeFileSync(specAbs, spec, "utf8");

  const vitestConfig = "vitest.config.ts";
  const profile = buildTypeormSqljsNestProfile({ sqljsResolvable: sqljsResolvable(sourceRoot), vitestConfig });
  const equivalentRows = JSON.stringify([{ [seedField]: "alpha" }, { [seedField]: "beta" }]);

  return {
    spec_path: specAbs,
    spec_rel: relative(sourceRoot, specAbs).split(/[\\/]+/).join("/"),
    target_symbol: resolved,
    entity_id: entityResolved,
    service_class: serviceClass,
    entity_class: entityClass,
    method,
    seed_field: seedField,
    runner: "vitest",
    vitest_config: vitestConfig,
    profile,
    genuine_mutation: { method, replacement: "return [];", replacement_mode: "return-json" },
    equivalent_mutation: { method, replacement: `return ${equivalentRows};`, replacement_mode: "return-json" }
  };
}
