import { afterEach, beforeAll, describe, expect, it } from "vitest";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";

import { opAnalyze } from "../../src/local/operations.js";
import { opRecipeDbSqljs, buildTypeormSqljsNestProfile } from "../../src/local/recipe/dbSqljs.js";
import { preloadTreeSitter } from "../../src/local/analyze/treeSitter/engine.js";
import { treeSitterLanguages } from "../../src/local/analyze/treeSitter/languages.js";

// Deterministic + offline: fixed clock, empty env (no provider keys → no LLM/network).
// These tests exercise the recipe GENERATOR and setup PROFILE only — no real oracle spawn.
// The end-to-end 0→1 proof + DB-3 live in scripts/smoke-db-sqljs-prove.mjs.
const deps = { clock: () => "2026-07-03T00:00:00Z", env: {} as NodeJS.ProcessEnv };
const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
const fixture = join(repoRoot, "tests/local/__fixtures__/db-sqljs-nest");

const TARGET = "sym:src/tag.service.ts#TagService.findAll";
const ENTITY = "src/tag.entity.ts#Tag";
const OUT = "orangepro_generated/tag-service.find-all.sqljs.spec.ts";
const VCFG = "vitest.config.ts";

const tempDirs: string[] = [];

beforeAll(async () => {
  await preloadTreeSitter(treeSitterLanguages());
});

afterEach(() => {
  while (tempDirs.length) {
    const dir = tempDirs.pop();
    if (dir) rmSync(dir, { recursive: true, force: true });
  }
});

/** Copy the checked-in fixture to a disposable source, analyze it, symlink node_modules
 *  so sql.js is resolvable (matches the smoke's exact-profile path). */
function setup(): { ws: string; source: string } {
  const dir = mkdtempSync(join(tmpdir(), "oprecipe-"));
  tempDirs.push(dir);
  const source = join(dir, "repo");
  const ws = join(dir, "ws");
  mkdirSync(ws);
  cpSync(fixture, source, { recursive: true });
  opAnalyze(ws, { source }, deps);
  symlinkSync(join(repoRoot, "node_modules"), join(source, "node_modules"), "dir");
  return { ws, source };
}

describe("recipe db-sqljs generator", () => {
  it("generates a real Nest sqljs spec that boots the module and never mocks the target", () => {
    const { ws, source } = setup();
    const res = opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: OUT, source });

    expect(res.target_symbol).toBe(TARGET);
    expect(res.runner).toBe("vitest");
    expect(existsSync(res.spec_path)).toBe(true);

    const spec = readFileSync(res.spec_path, "utf8");
    // Generated header + framework-native assertions.
    expect(spec.startsWith("// GENERATED BY OrangePro")).toBe(true);
    expect(spec).toContain('import { afterAll, beforeAll, describe, expect, it } from "vitest"');
    expect(spec).toContain("expect(rows");
    // Boots the smallest Nest testing module against an in-memory sqljs datasource.
    expect(spec).toContain('import "reflect-metadata"');
    expect(spec).toContain("Test.createTestingModule");
    expect(spec).toContain('type: "sqljs"');
    expect(spec).toContain("TypeOrmModule.forFeature([Tag])");
    expect(spec).toContain("providers: [TagService]");
    // Imports and calls the REAL target service — never mocks/replaces it.
    expect(spec).toContain('import { TagService } from "../src/tag.service"');
    expect(spec).toContain('import { Tag } from "../src/tag.entity"');
    expect(spec).toContain("service.findAll()");
    expect(spec).not.toMatch(/\b(vi|jest)\.mock\b/);
    expect(spec).not.toMatch(/mockImplementation|mockReturnValue/);

    // DB-3 validation plan: genuine inert sentinel + behavior-preserving equivalent.
    expect(res.genuine_mutation.replacement).toBe("return [];");
    expect(res.equivalent_mutation.replacement).toContain('"name":"alpha"');
  });

  it("emits an exact typeorm-sqljs-nest profile with no runtime setup when sql.js is resolvable", () => {
    const { ws, source } = setup();
    const res = opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: OUT, source });
    expect(res.profile.id).toBe("typeorm-sqljs-nest");
    expect(res.profile.confidence).toBe("exact");
    expect(res.profile.setup_commands).toEqual([]);
    expect(res.profile.test_env).toEqual([]);
  });

  it("refuses an ineligible target (non-entrypoint entity symbol)", () => {
    const { ws, source } = setup();
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: "sym:src/tag.entity.ts#Tag", entity: ENTITY, out: OUT, source })
    ).toThrow(/not an eligible provable target/);
  });

  it("refuses a target that does not resolve to a CodeSymbol", () => {
    const { ws, source } = setup();
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: "sym:src/tag.service.ts#Ghost.method", entity: ENTITY, out: OUT, source })
    ).toThrow(/did not resolve/);
  });

  it("rejects --entity that escapes the source root (containment)", () => {
    const { ws, source } = setup();
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: "../../outside.ts#Outside", out: OUT, source })
    ).toThrow(/relative path inside the source root/);
  });

  it("refuses --entity that does not resolve to a CodeSymbol in the graph", () => {
    const { ws, source } = setup();
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: "src/tag.entity.ts#Ghost", out: OUT, source })
    ).toThrow(/did not resolve to an existing CodeSymbol/);
  });

  it("refuses to overwrite an existing spec", () => {
    const { ws, source } = setup();
    opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: OUT, source });
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: OUT, source })
    ).toThrow(/refusing to overwrite/);
  });

  it("rejects --out that escapes the source root", () => {
    const { ws, source } = setup();
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: "../evil.spec.ts", source })
    ).toThrow(/relative path inside the source root|must live under/);
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: "orangepro_generated/../../evil.spec.ts", source })
    ).toThrow(/relative path inside the source root|must live under/);
  });

  it("rejects --out outside orangepro_generated/", () => {
    const { ws, source } = setup();
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: "src/tag.spec.ts", source })
    ).toThrow(/must live under orangepro_generated/);
  });

  it("rejects a non-spec --out", () => {
    const { ws, source } = setup();
    expect(() =>
      opRecipeDbSqljs(ws, { target_symbol: TARGET, entity: ENTITY, out: "orangepro_generated/tag.ts", source })
    ).toThrow(/\.spec\.ts/);
  });
});

describe("typeorm-sqljs-nest setup profile", () => {
  it("rejects a secret-looking test_env key", () => {
    expect(() =>
      buildTypeormSqljsNestProfile({ sqljsResolvable: true, testEnv: ["DATABASE_PASSWORD=hunter2"], vitestConfig: VCFG })
    ).toThrow(/secret-looking test_env/);
  });

  it("passes non-secret test_env through on the exact profile", () => {
    const profile = buildTypeormSqljsNestProfile({ sqljsResolvable: true, testEnv: ["NODE_ENV=test"], vitestConfig: VCFG });
    expect(profile.confidence).toBe("exact");
    expect(profile.setup_commands).toEqual([]);
    expect(profile.test_env).toEqual(["NODE_ENV=test"]);
  });

  it("emits a candidate install profile (not auto-run) when sql.js is missing", () => {
    const profile = buildTypeormSqljsNestProfile({ sqljsResolvable: false, vitestConfig: VCFG });
    expect(profile.confidence).toBe("candidate");
    expect(profile.setup_commands).toHaveLength(1);
    expect(profile.setup_commands[0].command).toBe("npm");
    expect(profile.setup_commands[0].args).toContain("install");
    expect(profile.setup_commands[0].args).toContain("sql.js");
    expect(profile.reason).toMatch(/not auto-run/i);
  });
});
